<a href="https://colab.research.google.com/github/Sudhaganisrinidhi/srinidhi/blob/main/probability_lab1basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a=[1,2,34,6,32,14,65,7]
arr=np.array(a)
print(arr)

arr=np.array([1,2,34,6,32,14,65,7])
print(arr)

print(arr[0])
print(arr[2])

aa=[[1,2,3,4],[4,2,3,6]]
A=np.array(aa)
print(A)

A=np.array([[1,2,3,4],[4,2,3,6]])
print(A)

print(type(A))

print(type(arr))

np.ndim(arr)

np.ndim(A)

print(np.size(arr))

print(np.size(A))

print(np.shape(arr))

print(np.shape(A))

A=np.array([[1,2,3],[3,4,5],[4,5,6]])
print(A)

print(A[0,:])
print(A[1,:])
print(A[2,:])

print(A[:,0])
print(A[:,1])
print(A[:,2])

print(A[2,1])

import pandas as pd

Dataset={
"State": ['Andhra Pradesh', 'Maharashtra', 'Karnataka', 'Kerala', 'Tamil Nadu'],
"Capital": ['Hyderabad', 'Mumbai', 'Bengaluru', 'Trivandrum', 'Chennai'],
"Literacy %": [89, 77, 82, 97,85],
"Avg High Temp(c)": [33, 30, 29, 31, 32 ]}
print(Dataset)

df = pd.DataFrame(Dataset)
print(df)

df = pd.DataFrame({
"State": ['Andhra Pradesh', 'Maharashtra', 'Karnataka', 'Kerala', 'Tamil Nadu'],
"Capital": ['Hyderabad', 'Mumbai', 'Bengaluru', 'Trivandrum', 'Chennai'],
"Literacy %": [89, 77, 82, 97,85],
"Avg High Temp(c)": [33, 30, 29, 31, 32 ]
})
print(df)
print(df.head(2))

print(df.tail(3))

print(df.dtypes)

print(df.sort_values('Literacy %', ascending=False))

print(df[['Capital']])

print(df[['State', 'Capital']])

print(df.loc[2])

print(df.iloc[2])

print(df.iloc[1,2])
print(df.loc[1,'Literacy %'])

a={"Distance":[15, 13, 16, 16, 15, 16, 17, 14, 15, 16, 16,17, 14, 17, 17, 16, 14, 15, 16, 17, 14, 16, 15, 17, 1]}
import pandas as pd
df=pd.DataFrame(a)
print(df)

print('The number of elements in the column is =',df['Distance'].size)

df2=pd.crosstab(index=df['Distance'],columns='Frequency')
print(df2)

print(df2['Frequency'].sum())
df2['Relative_Frequencies']=df2['Frequency']/df2['Frequency'].sum()
df2['Percentage']=df2['Frequency']/df2['Frequency'].sum()*100
print(df2)

df2.loc['Total']=df2.sum()
print(df2)
import numpy as np
import pandas as pd

data=[328, 470, 405, 375, 298, 326, 276, 362, 410, 255, 391, 370, 455, 229, 300, 183,
283, 366, 400, 495, 215, 157, 374, 306, 280, 409, 321, 269, 398, 200]
diction={"Score":data}
df=pd.DataFrame(diction)
print(df)

A=min(data)
print('The lowest value is ',A)
B=max(data)
print('The highestest value is ',B)

N=round((B-A)/50)
N

bins=np.linspace(150,500,N+1)
print(bins)

df['Class Intervals']=pd.cut(df['Score'],bins=bins,right=False,)
print(df)

table2=pd.crosstab(index=df['Class Intervals'],columns='Frequency')

table2



[ 1  2 34  6 32 14 65  7]
[ 1  2 34  6 32 14 65  7]
1
34
[[1 2 3 4]
 [4 2 3 6]]
[[1 2 3 4]
 [4 2 3 6]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
8
8
(8,)
(2, 4)
[[1 2 3]
 [3 4 5]
 [4 5 6]]
[1 2 3]
[3 4 5]
[4 5 6]
[1 3 4]
[2 4 5]
[3 5 6]
5
{'State': ['Andhra Pradesh', 'Maharashtra', 'Karnataka', 'Kerala', 'Tamil Nadu'], 'Capital': ['Hyderabad', 'Mumbai', 'Bengaluru', 'Trivandrum', 'Chennai'], 'Literacy %': [89, 77, 82, 97, 85], 'Avg High Temp(c)': [33, 30, 29, 31, 32]}
            State     Capital  Literacy %  Avg High Temp(c)
0  Andhra Pradesh   Hyderabad          89                33
1     Maharashtra      Mumbai          77                30
2       Karnataka   Bengaluru          82                29
3          Kerala  Trivandrum          97                31
4      Tamil Nadu     Chennai          85                32
            State     Capital  Literacy %  Avg High Temp(c)
0  Andhra Pradesh   Hyderabad          89                33
1     Maharashtra      Mumbai          77

col_0            Frequency
Class Intervals           
[150.0, 200.0)           2
[200.0, 250.0)           3
[250.0, 300.0)           6
[300.0, 350.0)           5
[350.0, 400.0)           7
[400.0, 450.0)           4
[450.0, 500.0)           3